### ISSUE TITLE
Transactions goes through but sendSmartTransaction returns timeout error

### ISSUE THREAD

**Issue by FractalH** [helius-labs/helius-sdk#102]
Had sendSmartTransaction function return `Transaction failed to confirm in 60s` even though the transaction was confirmed, (_causing the user to make a new one not knowing the first one went through_), it just throws that error it doesn't return any tx id so I can't check confirmation status in the code.

**Comment by tavindev** [comment]
I'm getting "Transaction failed to confirm within lastValidBlockHeight" error, but the transaction still goes through 🤔.
Looks like it's still broken. Maybe we should add an offset to the lastValidBlockHeight @0xIchigo?
