### ISSUE TITLE
createSmartTransaction `serialize` requiring all signatures

### ISSUE THREAD

**Issue by chukwumaokere** [helius-labs/helius-sdk#111]
Is there a possibility in which we can modify serialize in createSmartTransactions to optionally not require all signatures?
https://github.com/helius-labs/helius-sdk/blob/main/src/RpcClient.ts#L596

Right now, when I want to create a smart transaction I get a serialize error due to the fact that signatures are missing. 
BUT this is expected in my flow where im creating the Transaction on the backend (using legacy transaction) and serializing it and sending it to the frontend to be signed by the client, then sending it back to the backend to be broadcasted.

**Comment by chukwumaokere** [comment]
The code im proposing we can use for serializing and encoding ` encode(transaction.serialize({requireAllSignatures: false, verifySignatures: true}))`

**Comment by 0xIchigo** [comment]
gm @chukwumaokere! I apologize for the inconvenience — I've finally gotten around to making a PR. Please look at the following and let me know what you think. Thanks! https://github.com/helius-labs/helius-sdk/pull/117

**Comment by 0xIchigo** [comment]
Can be considered closed by #117
