### ISSUE TITLE
mintCompressedNft() method with collection parameter

### ISSUE THREAD

**Issue by alexandr-kazakov** [helius-labs/helius-sdk#116]
This example from the project README file:

``` js
import { Helius } from "helius-sdk";

const helius = new Helius("YOUR_API_KEY");
const response = await helius.mintCompressedNft({
  name: "Exodia the Forbidden One",
  symbol: "ETFO",
  owner: "OWNER_WALLET_ADDRESS",
  description:
    "Exodia the Forbidden One is a powerful, legendary creature composed of five parts: the Right Leg, Left Leg, Right Arm, Left Arm, and the Head. When all five parts are assembled, Exodia becomes an unstoppable force.",
  attributes: [
    {
      trait_type: "Type",
      value: "Legendary",
    },
    {
      trait_type: "Power",
      value: "Infinite",
    },
    {
      trait_type: "Element",
      value: "Dark",
    },
    {
      trait_type: "Rarity",
      value: "Mythical",
    },
  ],
  imageUrl:
    "https://cdna.artstation.com/p/assets/images/images/052/118/830/large/julie-almoneda-03.jpg?1658992401",
  externalUrl: "https://www.yugioh-card.com/en/",
  sellerFeeBasisPoints: 6900,
});
console.log(response.result);
```

Can you show me the same example but with **_collection_** parameter please? I want to mint cNFT and add it to my collection but if I use collection parameter I always get **`Program Error: "Instruction #2 Failed - Invalid collection authority"`**

**Comment by 0xIchigo** [comment]
gm @alexandr-kazakov! If you'd like to mint a cNFT to your own collection, you'll have to delegate Helius as a collection authority (using the `DelegateCollectionAuthority` method), so that Helius can mint to that collection on your behalf. We outline the entire process [here in the README](https://github.com/helius-labs/helius-sdk?tab=readme-ov-file#delegatecollectionauthority-and-revokecollectionauthority)

**Comment by 0xIchigo** [comment]
I'm going to go ahead and close this issue. If you have any further questions, please feel free to reach out to us via Discord or by creating a support chat on the Helius developer dashboard. Thanks!
