### ISSUE TITLE
token_info needs to be added to GetAssetResponse

### ISSUE THREAD

**Issue by llegoelkelo** [helius-labs/helius-sdk#119]
Related to #62

**Comment by 0xIchigo** [comment]
gm! [`token_info` has been added to `GetAssetResponse` already](https://github.com/helius-labs/helius-sdk/pull/99) — have you updated the SDK to the latest version 1.3.4?

**Comment by llegoelkelo** [comment]
just did and indeed it is there. thank you (closing)
