### ISSUE TITLE
[BUG] bs58.encode is not a function，，Error sending smart transaction: TypeError: bs58.encode is not a function

### ISSUE THREAD

**Issue by lin1792** [helius-labs/helius-sdk#120]
The dependency bs58 is missing, but it is used in the RpcClient.ts file, resulting in an error message about createSmartTransaction and createSmartTransactionWithTip

**Comment by lin1792** [comment]
And bs58.encode should be changed to bs58.default.encode

**Comment by 0xIchigo** [comment]
gm! It seems like this might be an issue with your environment — I'd recommend clearing your cache and reinstalling the SDK. However, I've also opened #122 to add `bs58` explicitly as a dependency to avoid issues like this in the future
