### ISSUE TITLE
Incorrect type of priority fee levels

### ISSUE THREAD

**Issue by livthomas** [helius-labs/helius-sdk#140]
When you use [getPriorityFeeEstimate](https://github.com/helius-labs/helius-sdk/blob/7a474512a1e64224fab473cf7d8c6ac902a9db98/src/RpcClient.ts#L430) function with `includeAllPriorityFeeLevels: true` parameter, the response looks like this:
```ts
{
  priorityFeeLevels: {
    min: 0,
    low: 0,
    medium: 10,
    high: 16381,
    veryHigh: 202510,
    unsafeMax: 333333333
  }
}
```
However, the [MicroLamportPriorityFeeLevels](https://github.com/helius-labs/helius-sdk/blob/7a474512a1e64224fab473cf7d8c6ac902a9db98/src/types/types.ts#L351-L358) type suggests that it should have `none` field instead of `min`.

**Comment by 0xIchigo** [comment]
This issue can be considered closed with the merging of #141
