### ISSUE TITLE
When can SWAP trading methods be added

### ISSUE THREAD

**Issue by epldlnwynn** [helius-labs/helius-sdk#147]
Nowadays, there are more and more SWAP transactions on Solana Chain. When can we add SWAP transaction methods.

**Comment by 0xIchigo** [comment]
We have the [SWAP transaction type](https://docs.helius.dev/resources/transaction-types) already available, so I assume you're referring to better parsing of swap txs. In that case, we will launch a v2 of our parsed transactions endpoint in the future with newer parsers. I don't have an exact ETA on that, but we'll keep the community updated
