### ISSUE TITLE
Add typescript type for transactionTypes while creating webhook

### ISSUE THREAD

**Issue by bhagyamudgal** [helius-labs/helius-sdk#15]
- Current typescript type for Webhook: 
<img width="361" alt="image" src="https://user-images.githubusercontent.com/76253604/219867700-f809e3cc-641a-4c0a-8b83-1b84212f78e3.png">
- We should add a typescript type (TransactionTypes) which is an array of all types Helius support at the moment mentioned here https://docs.helius.xyz/reference/transaction-types and assign it to transactionTypes instead of using string[] for better developer experience.

**Comment by 0xIchigo** [comment]
Closed by #78
