### ISSUE TITLE
DAS search asset delegate type should be `string`

### ISSUE THREAD

**Issue by joefitter** [helius-labs/helius-sdk#63]
This field allows a string delegate address to be included when searching assets. It doesn't return anything if a number is used.

https://github.com/helius-labs/helius-sdk/blob/0fdf3f941cec356f658ffab27f2dea521ee3c42c/src/types/das-types.ts#L73

**Comment by 0xIchigo** [comment]
Thank you for raising this issue! With #73 merged, this issue should be resolved in the next SDK release
