### ISSUE TITLE
DAS get asset response list, grand total is a number, not boolean

### ISSUE THREAD

**Issue by joefitter** [helius-labs/helius-sdk#64]
In this context, grand_total is a `number` or `undefined`, not `boolean`.

https://github.com/helius-labs/helius-sdk/blob/0fdf3f941cec356f658ffab27f2dea521ee3c42c/src/types/das-types.ts#L139C17-L139C24

**Comment by 0xIchigo** [comment]
Nice catch! This is closed by #82 and is live in version 1.3.1
