### ISSUE TITLE
TransactionEvent.compressed should be an array

### ISSUE THREAD

**Issue by deliversolana** [helius-labs/helius-sdk#76]
The `events` (TransactionEvent)  property of `EnrichedTransaction` should have an array when the burned asset is a compressed NFT, but instead the declared type is `CompressedNftEvent | null`.

See: https://github.com/helius-labs/helius-sdk/blob/main/src/types/types.ts#L228

**Comment by 0xIchigo** [comment]
gm @deliversolana! We had #69 address this issue, and we need to cut a new release for the SDK for it to go live. Is this what you're referring to, or is there something else I'm missing?

**Comment by 0xIchigo** [comment]
Closed by #69
